//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstProjectframework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeInfoEntities : DbContext
    {
        public EmployeeInfoEntities()
            : base("name=EmployeeInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmailTable> EmailTables { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<reviewTable> reviewTables { get; set; }
    }
}
